### ISSUE TITLE
error when run python run_tracker.py segm default_params --dataset vot18 --sequence ball1 --debug 1

### ISSUE THREAD

**Issue by ahmedosamaz** [alanlukezic/d3s#20]
when i run python run_tracker.py segm default_params --dataset vot18 --sequence ball1 --debug 1 
i got an error that

(pytracking) E:\master\Tracking\VOT\python vot\Trackers\d3s-master(1)\pytracking>python run_tracker.py segm default_params --dataset vot18 --sequence ball1 --debug 1
Traceback (most recent call last):
  File "run_tracker.py", line 84, in <module>
    main()
  File "run_tracker.py", line 80, in main
    run_tracker(args.tracker_name, args.tracker_param, args.runid, args.dataset, args.sequence, args.debug, args.threads)
  File "run_tracker.py", line 44, in run_tracker
    dataset = VOT18Dataset()
  File "..\pytracking\evaluation\vot18dataset.py", line 7, in VOT18Dataset
    return VOTDatasetClass().get_sequence_list()
  File "..\pytracking\evaluation\vot18dataset.py", line 24, in __init__
    self.sequence_list = self._get_sequence_list()
  File "..\pytracking\evaluation\vot18dataset.py", line 54, in _get_sequence_list
    sequence_list = pandas.read_csv(list_path, header=None, squeeze=True).values.tolist()
  File "C:\Users\Ahmed Osama\anaconda3\envs\pytracking\lib\site-packages\pandas\io\parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Ahmed Osama\anaconda3\envs\pytracking\lib\site-packages\pandas\io\parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\Ahmed Osama\anaconda3\envs\pytracking\lib\site-packages\pandas\io\parsers.py", line 946, in __init__
    self._make_engine(self.engine)
  File "C:\Users\Ahmed Osama\anaconda3\envs\pytracking\lib\site-packages\pandas\io\parsers.py", line 1178, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\Ahmed Osama\anaconda3\envs\pytracking\lib\site-packages\pandas\io\parsers.py", line 2008, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
OSError: [Errno 22] Invalid argument: 'E:\\master\\Tracking\\VOT\\python vot\x0bot-workspace/list.txt'

can you help me to run this tracker
im using python 3.8
windows 10
anaconda sw

**Comment by xiankgx** [comment]
Probably backslash in the path should be replaced with forward slash.
