### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

### ISSUE THREAD

**Issue by mrlonely426** [alanlukezic/d3s#29]
Traceback (most recent call last):
  File "run_tracker.py", line 84, in <module>
    main()
  File "run_tracker.py", line 80, in main
    run_tracker(args.tracker_name, args.tracker_param, args.runid, args.dataset, args.sequence, args.debug, args.threads)
  File "run_tracker.py", line 65, in run_tracker
    run_dataset(dataset, trackers, debug, threads)
  File "../pytracking/evaluation/running.py", line 54, in run_dataset
    run_sequence(seq, tracker_info, debug=debug)
  File "../pytracking/evaluation/running.py", line 21, in run_sequence
    tracked_bb, exec_times = tracker.run(seq, debug=debug)
  File "../pytracking/evaluation/tracker.py", line 58, in run
    output_bb, execution_times = tracker.track_sequence(seq)
  File "../pytracking/tracker/base/basetracker.py", line 35, in track_sequence
    self.initialize(image, sequence.init_state)
  File "../pytracking/tracker/segm/segm.py", line 160, in initialize
    self.init_optimization(train_x, init_y)
  File "../pytracking/tracker/segm/segm.py", line 215, in init_optimization
    self.joint_optimizer.run(self.params.init_CG_iter // self.params.init_GN_iter, self.params.init_GN_iter)
  File "../pytracking/libs/optimization.py", line 345, in run
    self.run_GN_iter(cg_iter)
  File "../pytracking/libs/optimization.py", line 390, in run_GN_iter
    delta_x, res = self.run_CG(num_cg_iter, eps=self.cg_eps)
  File "../pytracking/libs/optimization.py", line 127, in run_CG
    q = self.A(self.p)
  File "../pytracking/libs/optimization.py", line 400, in A
    dfdx_x = torch.autograd.grad(self.dfdxt_g, self.g, x, retain_graph=True)
  File "/home/xl/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/autograd/__init__.py", line 157, in grad
    inputs, allow_unused)
 
when i run 'python run_tracker.py segm default_params --dataset vot18 --debug 1,the error occurred,'Is there anybody have the same issue

**Comment by JianLeer** [comment]
Same

**Comment by mrlonely426** [comment]
> Same

**Comment by mrlonely426** [comment]
I have solved the issue by changing the version of pytorch.

**Comment by johnsoncn** [comment]
conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch
