### ISSUE TITLE
cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

### ISSUE THREAD

**Issue by jiaqinxu** [alanlukezic/d3s#33]
Traceback (most recent call last):
  File "run_video.py", line 36, in <module>
    main()
  File "run_video.py", line 32, in main
    run_video(args.tracker_name, args.tracker_param,args.videofile, args.optional_box, args.debug)
  File "run_video.py", line 20, in run_video
    tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=debug)
  File "../pytracking/evaluation/tracker.py", line 77, in run_video
    tracker.track_videofile(videofilepath, optional_box)
  File "../pytracking/tracker/base/basetracker.py", line 91, in track_videofile
    self.initialize(frame, init_state)
  File "../pytracking/tracker/segm/segm.py", line 160, in initialize
    self.init_optimization(train_x, init_y)
  File "../pytracking/tracker/segm/segm.py", line 215, in init_optimization
    self.joint_optimizer.run(self.params.init_CG_iter // self.params.init_GN_iter, self.params.init_GN_iter)
  File "../pytracking/libs/optimization.py", line 345, in run
    self.run_GN_iter(cg_iter)
  File "../pytracking/libs/optimization.py", line 390, in run_GN_iter
    delta_x, res = self.run_CG(num_cg_iter, eps=self.cg_eps)
  File "../pytracking/libs/optimization.py", line 127, in run_CG
    q = self.A(self.p)
  File "../pytracking/libs/optimization.py", line 400, in A
    dfdx_x = torch.autograd.grad(self.dfdxt_g, self.g, x, retain_graph=True)
  File "/home/chenzhe/anaconda3/envs/D3Spytracking/lib/python3.7/site-packages/torch/autograd/__init__.py", line 157, in grad
    inputs, allow_unused)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

I use the same cuda version with Dimp(pytracking)，it works in dimp but error here，how can i solve it?

**Comment by jiaqinxu** [comment]
I saw an answer says change the pytorch version , I tried to use 
# CUDA 10.0
conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch
and run it successfully
